# Generated by Django 4.2 on 2025-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='aircraft',
            field=models.CharField(choices=[('General Aviation', 'General Aviation'), ('Commercial', 'Commercial'), ('Military', 'Military')], max_length=100),
        ),
    ]
