# Generated by Django 4.2 on 2025-03-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='fuel_on_arrival',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='fuel_on_departure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='soul_on_board',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
