# Generated by Django 4.2 on 2025-03-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_fuel_on_arrival_log_fuel_on_departure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='soul_on_board',
            new_name='souls_on_board',
        ),
    ]
