# Generated by Django 4.2 on 2025-03-05 13:14

from django.db import migrations, models
import logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_rename_soul_on_board_log_souls_on_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='aircraft_registration',
            field=models.CharField(max_length=100, validators=[logs.models.is_aircraft_reg_num_valid]),
        ),
    ]
