# Generated by Django 4.2 on 2025-03-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_log_aircraft_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='aircraft_registration',
            field=models.CharField(max_length=100),
        ),
    ]
