# Generated by Django 4.2 on 2025-03-10 10:14

from django.db import migrations, models
from datetime import datetime, time
import django.utils.timezone

def update_existing_dates(apps, schema_editor):
    Log = apps.get_model('logs', 'Log')  # Get the Log model dynamically
    for log in Log.objects.all():  # Loop through all existing records
        log.date = datetime.combine(log.date, time(0, 0, 0))  # Combine the current date with time 00:00:00
        log.save()

class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_log_aircraft_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(update_existing_dates),  # Call the function to update existing dates
    ]
