# Generated by Django 4.2 on 2025-03-12 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0008_pilot_certification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pilot_Certification',
            new_name='PilotCertification',
        ),
    ]
