# Generated by Django 4.2 on 2025-03-15 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0009_rename_pilot_certification_pilotcertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_registration', models.CharField(max_length=100)),
                ('maintenance_date', models.DateField()),
                ('issue_reported', models.TextField()),
                ('fix_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_conditions', models.CharField(max_length=100)),
                ('wind_speed', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.log')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=100)),
                ('completion_date', models.DateField()),
                ('instructor_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Captain', 'Captain'), ('First Officer', 'First Officer'), ('Instructor', 'Instructor')], max_length=50)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('description', models.TextField(blank=True, null=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.log')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=100)),
                ('actions_taken', models.TextField()),
                ('outcome', models.TextField()),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.log')),
            ],
        ),
    ]
