# Generated by Django 4.2 on 2025-03-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_maintenancereport_weatherreport_trainingrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightcrewassignment',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='logs.log'),
        ),
        migrations.AlterField(
            model_name='flightcrewassignment',
            name='role',
            field=models.CharField(choices=[('Captain', 'Captain'), ('First Officer', 'First Officer'), ('Instructor', 'Instructor'), ('Flight Engineer', 'Flight Engineer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='weather_conditions',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy'), ('Foggy', 'Foggy'), ('Snowy', 'Snowy'), ('Windy', 'Windy'), ('Rainy & Foggy', 'Rain & Foggy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
