# Generated by Django 4.2 on 2025-03-15 09:54

import django.core.validators
from django.db import migrations, models
import logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0011_alter_flightcrewassignment_log_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcrewassignment',
            name='number_of_crew',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='flightattachment',
            name='file',
            field=models.FileField(upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='log',
            name='aircraft_registration',
            field=models.CharField(max_length=100, validators=[logs.models.is_aircraft_reg_num_valid]),
        ),
    ]
