# Generated by Django 4.2 on 2025-03-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_flightcrewassignment_number_of_crew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancereport',
            name='maintenance_date',
        ),
        migrations.AddField(
            model_name='maintenancereport',
            name='log_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logs.log'),
            preserve_default=False,
        ),
    ]
